<?php
/*

Template Name: Coronavirus Page

 */

get_header('');
?>

	
	<section class="p-0 position-relative">
		<div class="container-fluid overlay-img-holder">
			<img src="<?php bloginfo('stylesheet_directory'); ?>/assets/img/who-we-are.jpg" class="w-100" alt="Image of front of Bedfont Scientific Ltd">
			<div class="overlay">
				<div class="col-12 col-md-6 mx-auto">
					<h1>Coronavirus & Bedfont<sup>®</sup> Products Update</h1>
					<p>COVID-19, more commonly referred to as Coronavirus, has become an increasing concern, especially in the world of medical devices.</p>
				</div>
			</div>
		</div>
		<!--<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="30px" viewBox="0 0 1280 140" preserveAspectRatio="none" style="position: absolute;bottom: 0;"><g fill="#fff"><path d="M1280 86c-19.9-17.21-40.08-39.69-79.89-39.69-57.49 0-56.93 46.59-115 46.59-53.61 0-59.76-39.62-115.6-39.62C923.7 53.27 924.26 87 853.89 87c-89.35 0-78.74-87-188.2-87C554 0 543.95 121.8 423.32 121.8c-100.52 0-117.84-54.88-191.56-54.88-77.06 0-100 48.57-151.75 48.57-40 0-60-12.21-80-29.51v54H1280z"></path></g></svg>-->
	</section>
	 <section>
	 	<div class="container">
			<div class="row">
				<div class="col-12 coronavirus">
					<p>COVID-19, more commonly referred to as Coronavirus, has become an increasing concern, especially in the world of medical devices. We have collated the following information to hopefully answer any questions you may have about the use of Bedfont<sup>®</sup> products and consumables. If you're ready to resume breath testing, <a href="breath-testing-in-covid-19" title="Click here for our Breath Testing in Covid-19 page">click here</a> to view our step by step guide.</p>
					<h2>My patient has cold/flu-like symptoms – can they still perform a breath test?</h2>
					<p>As a global company, we must first and foremost advise that you follow your local guidelines on whether or not you should continue breath testing at this time.</p>
					<p>Please be advised that patients with cold/flu-like symptoms can pose a higher risk of cross infection.</p>
					<h2>What precautions can I take to reduce the risk of cross-infection?</h2>
					<p>At this time, Bedfont<sup>®</sup> suggests the following measures to help reduce the risk of cross-infection:</p>
					<ul>
						<li>Throughout the consultation, wear disposable gloves and other PPE such as a facemask. Wash hands before and after as per your clinical guidelines</li>
						<li>Ensure the area is well ventilated</li>
						<li>Ensure to maintain the minimum, recommended distance from patients as per your clinical guidelines, <strong>please note:</strong> none of Bedfont<sup>®</sup> breath monitors require a test technique that generates aerosols. A list of aerosol generating procedures (AGP) can be <a href="https://www.gov.uk/government/publications/wuhan-novel-coronavirus-infection-prevention-and-control/covid-19-infection-prevention-and-control-guidance-aerosol-generating-procedures" title="Click here for the website" target="_blank">found here.</a></li>
						<li>Healthcare professionals should allow their patient to hold the monitor when carrying out a breath test. Once the breath test has been completed, the monitor should be cleaned with anti-viral and anti-bacterial wipes provided with the monitor. The mouthpiece should be disposed of in accordance to the local infection control guidelines</li>
						<li>Ensure a multi-patient use D-piece<sup>™</sup> is used with a fresh single-use, individually wrapped SteriBreath<sup>™</sup> Eco mouthpiece and disposed of as per the IFU, alternatively you can opt for the single-use OneBreath<sup>™</sup> mouthpiece or to use the D-piece<sup>™</sup> once.</li>
						<li>It is recommended at all times that the patient should open, use and dispose of their mouthpiece at the end of the test, as stated in the <a href="downloads/LAB286 ICMG - Issue 13.pdf" title="Click for the document">Infection Control Maintenance Guidelines</a>.</li>
						<li>As standard practice, Bedfont<sup>®</sup> recommends that the monitors are wiped down with the provided, non-alcoholic, antibacterial/viral wipes, after each breath test.</li>
					</ul>
					<h2>I’m trying to identify a cleaning product that is effective against Coronavirus and also safe for our devices. I know that we aren’t supposed to use alcohol products for example.</h2>
					<p>NHS customers should follow procedures given by the NHS and the rest of the world should please follow their local guidelines, followed by the <a href="downloads/LAB286 ICMG - Issue 13.pdf" title="Click for the document">Infection Control and Maintenance Guidelines</a> provided by Bedfont<sup>®</sup>.</p>
					<p>As standard practice, Bedfont<sup>®</sup> recommends that the monitors are wiped down with non-alcoholic antibacterial/viral wipes, provided with the monitor, after each breath test.</p>
					<p>The World Health Organisation has labelled the latest strain of coronavirus as Covid-19. The virus that causes the disease has been named as SARS-CoV-2. The Azo Universal wipes recommended by Bedfont<sup>®</sup> have been tested by the supplier and found effective against SARS-CoV-2, as the product shows efficacy against feline coronavirus, a surrogate coronavirus for SARS-CoV-2. A test report can be shown on request.</p>
					<p>We have also conducted testing on a 0.5% Sodium Hypochlorite solution, which was found be effective against SARS-CoV-2. Testing found that a solution of this strength had little effect on the readings and we can safely confirm that Sodium Hypochlorite with a solution ≤0.5% can be applied directly to the Smokerlyzer<sup>®</sup>, NObreath<sup>®</sup>, ToxCO<sup>®</sup> and Gastro<sup>+™️</sup> monitors for cleaning. Test reports (138.322, 141.127, 120.241 and 120.242) can be shown on request. </p>
					<p>Please see the next question about hand sanitiser containing alcohol.</p>
					<h2>I know we cannot use alcohol to clean the products, but can I still use a hand sanitiser containing alcohol before using the monitor?</h2>
					<p>During the current COVID-19 risk, we understand that using only non-alcohol sanitising products may not be feasible at this time. It is for this reason that we have tested the potential impact alcohol hand sanitising gels might have on device results. From the data obtained, it appears that commonly used hand sanitisers contain up to 73.5% alcohol, therefore we have carried out strenuous testing with a number of hand gels up to this alcohol percentage, using the monitors after the hand sanitiser has completely dried.</p>
					<p>After using and allowing hand sanitiser to dry, it was shown to have little effects on the results given by the Smokerlyzer<sup>®</sup>, ToxCO<sup>®</sup> and NObreath<sup>®</sup> range of products. <strong>Therefore, we can conclude that hand sanitising products with an alcohol content lower than 73.5% can be used when handling the Smokerlyzer<sup>®</sup>, ToxCO<sup>®</sup> and NObreath<sup>®</sup> monitors, once hands have dried.</strong></p>
					<p>If you are worried the sensor is reading incorrectly, please check accuracy of the sensor using the CO that is supplied by Bedfont<sup>®</sup> (please refer to user manual about how to do this). Alternatively, you can send the device back to Bedfont<sup>®</sup>/distributor so we can check your device is performing correctly</p>
					<p>Alcohol sanitisers containing more than 73.5% alcohol should be avoided due to the lack of testing with regard to the impact it could have on readings.</p>
					<p>A device accuracy test should be performed periodically to ensure the monitor is working as intended. This can be done with a canister of gas, which can be purchased from Bedfont<sup>®</sup>.</p>
					<h2>How effective is SteriTouch<sup>®</sup> against Coronavirus?</h2>
					<p>We are proud to say the Bedfont<sup>®</sup> monitors are integrated with SteriTouch<sup>®</sup> antimicrobial additives, which eradicate the bacteria and viruses that cause contamination and infection. SteriTouch<sup>®</sup> has released a statement on COVID-19 which reads, ‘Several of the active substances used by SteriTouch<sup>®</sup> have been successfully tested against other enveloped viruses, such as Influenza, Avian flu and SARS. It would be reasonable to imply that those same active substances would be effective against COVID-19, but at this stage testing against COVID-19 is not available.’<sup>3</sup></p>
					<p>If you would like to take extra precautions at this time, Bedfont<sup>®</sup> recommends wearing gloves when handling the monitors and instead opting for the single-use OneBreath<sup>™</sup> mouthpiece, which contains a one-way valve and has be proven to remove and trap 99% and 97% of airborne bacteria and viruses respectively. NHS customers should follow procedures given by the NHS followed by the <a href="downloads/LAB286 ICMG - Issue 13.pdf" title="Click for the document">Infection Control and Maintenance Guidelines</a> provided by Bedfont<sup>®</sup>.</p>
					<h2>I’ve heard breath tests can generate aerosols (known as ‘aerosol generating procedures’/AGP’s), which will increase the chances of cross-infection. Is this the case for Bedfont<sup>®</sup> devices?</h2>
					<p>The breath testing procedures for all of Bedfont<sup>®</sup>’s monitors do not require patients to forcefully exhale, only to gently exhale at a steady pace until the test is complete. For this reason, completing a breath test on a Bedfont</up>®</sup> device (NObreath<sup>®</sup>, Smokerlyzer<sup>®</sup>, Gastrolyzer<sup>®</sup> and ToxCO<sup>®</sup> monitors) is not considered as an AGP, as deemed by Public Health England<sup>13</sup>.</p>
					<p>There have been no reports of coughing experienced from the use of use of any of Bedfont<sup>®</sup> Scientific’s breath analysis products. The recent clinical studies and all usability studies performed to date examining the monitors safety and performance show that there have been no coughing related events.</p>
					<h2>How safe are the D-piece<sup>™</sup> mouthpiece filters?</h2>
					<p>The D-piece</sup>™</sup> incorporates a one-way valve and an infection control filter, which has been tested vigorously by Public Health England to prove it removes and trap 99% and 97% of airborne bacteria and viruses respectively. Bedfont<sup>®</sup> recommends the D-piece™ can be used for a continuous 30 days in conjunction with single-patient-use SteriBreath™ mouthpieces.</p>
					<p>Both the D-piece<sup>™</sup> filter and OneBreath™ mouthpiece have been tested to filter viruses as small as 24 nanometres in diameter and the Covid-19 virus particle has a diameter of approximately 125 nanometres<sup>1</sup>. Due to the risky nature of testing live respiratory viruses, a non-pathogenic virus model is used (M2-Coliphage). The filters undergo both bacterial filter efficiency (BFE) and viral filtration efficiency (VFE). The virus model is incredibly penetrable, even more so than a majority of human viruses, therefore makes it a very effective model to use for virus filtration efficiency (VFE) testing. The model virus is approximately 24-26 nanometres in size<sup>1</sup> in comparison to COVID-19 virus which is approximately 125 nanometres in size<sup>2</sup>. Therefore, Bedfont<sup>®</sup> can conclude that bacterial and viral pathogens (including COVID-19) will effectively be removed by both the  D-piece<sup>™</sup> filter and OneBreath™ mouthpiece filter at an efficiency rate of >99% (bacteria) and >97% (viruses).</p>
					<p>Please note the D-piece<sup>™</sup>, intended for use with Smokerlyzer<sup>®️</sup> CO monitors, includes a bacterial and viral infection control filter and is a trademarked consumable manufactured by Bedfont<sup>®️</sup>. It is not to be confused with other plastic parts provided by other CO monitor manufacturers, which may not include any infection control filters. Any parts claimed to be “D pieces”, which are not provided by Bedfont<sup>®️</sup> Scientific Ltd., are not only fraudulent but do not filter out >99% and >97% of airborne bacteria and viruses respectively.</p>
					<p>Furthermore, at Bedfont<sup>®</sup>, we take great pride manufacturing the most innovative and high-quality products. Being a medical manufacturer means there are a lot of classifications and regulations that we must adhere to regarding our products. We are pleased to say our consumables are manufactured in a certified class 100k clean room, which is the 2nd highest classification for particle filtration (ISO Class 8 against ISO14644-1), guaranteeing cleanliness and quality.</p>
					<h2>How safe is the 2<sup>nd</sup> generation NObreath<sup>®</sup> mouthpiece?</h2>
					<p>The 2<sup>nd</sup> generation NObreath<sup>®</sup> mouthpiece has been tested by Public Health England to prove it removes and trap >99% and >98% of airborne bacteria and viruses respectively<sup>10</sup>. The 2<sup>nd</sup> generation NObreath<sup>®</sup> mouthpiece has been designed to be single-patient use, this means once the mouthpiece has been used by the patient, you must dispose of the mouthpiece following local waste guidelines in-line with Bedfont<sup>®</sup>’s recommendations and to further minimise the risk of cross infection.</p>
					<p>The 2<sup>nd</sup> NObreath<sup>®</sup> mouthpiece has been tested to filter viruses as small as 24 nanometres in diameter and the COVID-19 virus particle has a diameter of approximately 125 nanometres<sup>1</sup>. Due to the risky nature of testing live respiratory viruses, a non-pathogenic virus model is used (M2-Coliphage). The filters undergo both bacterial filter efficiency (BFE) and viral filtration efficiency (VFE). The virus model is incredibly penetrable, even more so than a majority of human viruses, therefore makes it a very effective model to use for virus filtration efficiency (VFE) testing. The model virus is approximately 24-26 nanometres in size<sup>1</sup> in comparison to COVID-19 virus which is approximately 125 nanometres in size<sup>2</sup>. Therefore, Bedfont<sup>®</sup> can conclude that bacterial and viral pathogens (including COVID-19) will effectively be removed by the 2<sup>nd</sup> generation NObreath<sup>®</sup> mouthpiece filter at an efficiency rate of >99%  for bacteria and >98% viruses<sup>9</sup>.</p>
					<h2>How safe is the 1<sup>st</sup> generation NObreath<sup>®</sup> mouthpiece?</h2>
					<p>The 1<sup>st</sup> generation NObreath<sup>®</sup> mouthpiece has been tested by Public Health England to prove it removes and trap >99% of airborne bacteria and viruses and contains a moisture removal filter. The 1<sup>st</sup> generation NObreath<sup>®</sup> mouthpiece has been designed to be single-patient use, this means once the mouthpiece has been used by the patient, you must dispose of the mouthpiece following local waste guidelines in-line with Bedfont<sup>®</sup>’s recommendations and to further minimise the risk of cross infection.</p>
					<p>The 1<sup>st</sup> generation NObreath<sup>®</sup> mouthpiece has been tested to filter viruses as small as 24 nanometres in diameter and the COVID-19 virus particle has a diameter of approximately 125 nanometres<sup>1</sup>. Due to the risky nature of testing live respiratory viruses, a non-pathogenic virus model is used (M2-Coliphage). The filters undergo both bacterial filter efficiency (BFE) and viral filtration efficiency (VFE). The virus model is incredibly penetrable, even more so than a majority of human viruses, therefore makes it a very effective model to use for virus filtration efficiency (VFE) testing. The model virus is approximately 24-26 nanometres in size1 in comparison to COVID-19 virus which is approximately 125 nanometres in size<sup>2</sup>. Therefore, Bedfont<sup>®</sup> can conclude that bacterial and viral pathogens (including COVID-19) will effectively be removed by the 1<sup>st</sup> generation NObreath<sup>®</sup> mouthpiece filter at an efficiency rate of >99%  for bacteria and viruses<sup>10</sup>.</p>
					<h2>How safe is the GastroCH<sub>4</sub>ECK<sup>®</sup> mouthpiece?</h2>
					<p>The GastroCH<sub>4</sub>ECK<sup>®</sup> mouthpiece has been tested by Public Health England to prove it removes and trap >99% of airborne bacteria and viruses<sup>9</sup>, and contains a moisture removal filter. The GastroCH<sub>4</sub>ECK<sup>®</sup> mouthpiece has been designed to be single-patient use, this means once the mouthpiece has been used by the patient, you must dispose of the mouthpiece following local waste guidelines in-line with Bedfont<sup>®</sup>’s recommendations and to further minimise the risk of cross infection.</p>
					<p>The GastroCH<sub>4</sub>ECK<sup>®</sup> mouthpiece has been tested to filter viruses as small as 24 nanometres in diameter and the COVID-19 virus particle has a diameter of approximately 125 nanometres1. Due to the risky nature of testing live respiratory viruses, a non-pathogenic virus model is used (M2-Coliphage). The filters undergo both bacterial filter efficiency (BFE) and viral filtration efficiency (VFE). The virus model is incredibly penetrable, even more so than a majority of human viruses, therefore makes it a very effective model to use for virus filtration efficiency (VFE) testing. The model virus is approximately 24-26 nanometres in size<sup>1</sup> in comparison to COVID-19 virus which is approximately 125 nanometres in size<sup>2</sup>. Therefore, Bedfont<sup>®</sup> can conclude that bacterial and viral pathogens (including COVID-19) will effectively be removed by the GastroCH<sub>4</sub>ECK<sup>®</sup> mouthpiece filter at an efficiency rate of >99% for bacteria and viruses<sup>10</sup>.</p>
					<h2>Can remote breath testing still be done with the GastroCH<sub>4</sub>ECK<sup>®</sup> Gastrolyzer<sup>®</sup> breath bags?</h2>
					<p>First and foremost we must ask that you follow your local guidelines on continuing Hydrogen and Methane Breath Testing (HMBT) at this time.</p>
					<p>The British Society of Gastroenterology have published their guidelines on carry out GI testing during these current conditions, and recommend home kits for HBMT procedures,  which allow patients to carry out the test at home instead of the hospital/clinic environment<sup>5</sup>.</p>
					<p>Therefore, when using the GastroCH<sub>4</sub>ECK<sup>®</sup> breath bags in home kits for remote HBMT testing, Bedfont<sup>®</sup> advises the following:</p>
					<ul>
						<li>A study published in the New England Journal of Medicine revealed plastic is the surface the virus remains viable on for the longest - up to 72 hours. On stainless steel, the virus was detected up to 48 hours after application. For cardboard it was 24 hours and for copper just 4 hours<sup>6</sup>. Therefore first consider leaving the samples in quarantine for 72 hours before sampling.</li>
						<li>Before sampling, wipe down the sample bags with non-alcoholic antibacterial/viral wipes, provided with the monitor.</li>
						<li>If you would like to take extra precautions at this time, Bedfont<sup>®</sup> recommends wearing gloves when handling the monitors and its consumables.</li>
						<li>As standard practice, Bedfont<sup>®</sup> recommends that the monitors are wiped down with non-alcoholic antibacterial/viral wipes, provided with the monitor, after each breath test/sample.</li>
					</ul>
					<h2>Can I use other mouthpieces/consumables to make it safer for my patients?</h2>
					<p>Use of counterfeit or non-Bedfont<sup>®</sup> approved accessories and consumables may result in loss of performance and/or damage to your device. This risk of incorrect results could adversely affect patient care. We also remind you that counterfeit and/or non-Bedfont<sup>®</sup> accessories and consumables do not possess the quality and reliability of the original manufacturer products, nor have they undergone the Toxicology tests to ensure they are fit to be used orally, and therefore their safety and infection control efficacy cannot be guaranteed.</p>
					<p>The D-piece™ has been tested by Public Health England to prove it removes and trap >99% and >97% of airborne bacteria and viruses respectively, and contains a one-way valve to prevent patient’s inhaling through the mouthpiece. Bedfont<sup>®</sup> recommends the D-piece™ can be used for a continuous 30 days in conjunction with single-patient-use SteriBreath™ Eco mouthpieces.</p>
					<p>If you have any concerns over multiple use of the D-piece™ mouthpiece filter, Bedfont<sup>®</sup> can also offer the OneBreath™ mouthpiece, which also contains a one-way valve and has been vigorously by Public Health England to prove it removes and trap >99% of airborne bacteria and >97% viruses. The OneBreath™ mouthpiece is single-use for ‘gold standard’ infection control and can be disposed of according to local waste guidelines immediately after testing to further minimise the risk of cross infection.</p>
					<h2>Is FeNO monitoring an aerosol generating procedures (AGP)?</h2>
					<p>Risks associated with performing lung function tests during the COVID-19 pandemic has been reviewed by established respiratory organisations. ARTP (Association for Respiratory Technology and Physiology) and PCRS (The Primary Care Respiratory Society) published guidance on FeNO testing during pandemic times. Both supported the idea that FeNO testing was a low effort procedure, therefore was unlikely to induce aerosol generating events, such as coughing<sup>7-8</sup>.</p>
					<p>Additionally, compared to other well established respiratory tests such as spirometry, FeNO testing has been considered a lower risk in comparison suggested in a statement released in September 2020 by PCRS<sup>8</sup>.</p>
					<p>The breath testing procedures for both the 1<sup>st</sup> and 2<sup>nd</sup> generation NObreath<sup>®</sup> FeNO monitors do not require patients to forcefully exhale, only to gently exhale at a steady pace until the test is complete. For this reason, breath testing, and FeNO monitoring in particular, are not considered as AGPs, as deemed by Public Health England<sup>13</sup>.</p>
					<p>There have been no reports of coughing experienced from the use of the 1<sup>st</sup> or 2<sup>nd</sup> generation NObreath<sup>®</sup>. The recent NObreath<sup>®</sup> clinical study and all usability studies performed since the launch of the 1<sup>st</sup> and 2<sup>nd</sup> generation NObreath<sup>®</sup> examining the monitors safety and performance show that there have been no coughing related events.</p>
					<br />
					<p>We are working around the clock to provide you with current and correct information. Please check back daily for all updates regarding Coronavirus and the Bedfont<sup>®</sup> products and consumables.</p>
					<p>If you wish to review any of the reports mentioned above, please email <a href="mailto:clinical@bedfont.com?subject=Contact From Bedfont Website - Corona Virus Page" title="Click here to contact customer service" >clinical@bedfont.com</a>.</p>
					<div class="covid-page-breath-testing">
						<h2 class="text-center text-white mt-2">Ready to resume breath testing?</h2>
						<p><a href="breath-testing-in-covid-19" title="Click here for our Breath Testing in Covid-19 page">Click here to view our helpful step by step guide on how to safely restart and conduct breath testing during COVID-19</a></p>
					</div>
					<h2>References</h2>
					<p>1. Berkeywaterkb.com. 2020. Is The MS2 – Fr Coliphage Still Known To Be A Good Indicator Of Virus Filtration? Do You Have Tests On Any Other Viruses? – Berkey Knowledge Base. [online] Available at: <a href="http://berkeywaterkb.com/is-the-ms2-fr-coliphage-still-known-to-be-a-good-indicator-of-virus-filtration-at-least-one-article-suggests-that-it-might-not-be-do-you-have-tests-on-any-other-viruses/#:~:text=The MS-2 virus is 24-26,both referenced on the chart" target="_blank" title="click to follow the page">http://berkeywaterkb.com/is-the-ms2-fr-coliphage-still-known-to-be-a-good-indicator-of-virus-filtration-at-least-one-article-suggests-that-it-might-not-be-do-you-have-tests-on-any-other-viruses/#:~:text=The MS-2 virus is 24-26,both referenced on the chart</a> [Accessed 12 June 2020].</p>
					<p>2. Avon-protection.com. 2020. [online] Available at: <a href="https://www.avon-protection.com/downloads/product_brochures/GR04471-01%20Coronavirus%20-%20WHITE%20PAPER.pdf" target="_blank" title="click here to follow the page">https://www.avon-protection.com/downloads/product_brochures/GR04471-01%20Coronavirus%20-%20WHITE%20PAPER.pdf</a> [Accessed 12 June 2020].</p>
					<p>3. SteriTouch. 2020. CORONAVIRUS – THE STERITOUCH STANCE. [online] Available at: <a href="https://www.steritouch.com/portfolio-posts/coronavirus-steritouch-stance/" target="_blank" title="click to follow the page">https://www.steritouch.com/portfolio-posts/coronavirus-steritouch-stance/</a> [Accessed 12 June 2020].</p>
					<p>4.NHS. 2020. Coronavirus (COVID-19). [online] Available at: <a href="https://www.nhs.uk/conditions/coronavirus-covid-19/" target="_blank" title="click to follow the page">https://www.nhs.uk/conditions/coronavirus-covid-19/</a> [Accessed 12 June 2020].</p>
					<p>5. The British Society of Gastroenterology. 2020. AGIP Council Guidance In Relation To GI Physiology Provision During The COVID-19 Pandemic | The British Society Of Gastroenterology. [online] Available at: <a href="https://www.bsg.org.uk/covid-19-advice/agip-council-guidance-in-relation-to-gi-physiology-provision-during-the-covid-19-pandemic/" target="_blank" title="Click here to follow the page">https://www.bsg.org.uk/covid-19-advice/agip-council-guidance-in-relation-to-gi-physiology-provision-during-the-covid-19-pandemic/</a> [Accessed 12 June 2020].</p>
					<p>6. New England Journal of Medicine. 2020. Aerosol And Surface Stability Of SARS-Cov-2 As Compared With SARS-Cov-1 | NEJM. [online] Available at: <a href="https://www.nejm.org/doi/full/10.1056/NEJMc2004973" target="_blank" title="Click here to follow the page">https://www.nejm.org/doi/full/10.1056/NEJMc2004973</a> [Accessed 12 June 2020].</p>
					<p>7.  Artp.org.uk. 2021 [Internet]. Artp-uk.org [cited 25 January 2021]. Available from: <a href="https://www.artp.org.uk/write/MediaUploads/Standards/COVID19/ARTP_COVID_Practical_Innovations_Vers1.2_final.pdf" target="_blank" title="click to follow the page">https://www.artp.org.uk/write/MediaUploads/Standards/COVID19/ARTP_COVID_Practical_Innovations_Vers1.2_final.pdf</a></p>
					<p>8.  PCRS Position Statement Diagnostic work up of the patient presenting with respiratory symptoms during the COVID-19 pandemic [Internet]. Pcrs-uk.org. 2021 [cited 25 January 2021]. Available from: <a href="https://www.pcrs-uk.org/sites/pcrs-uk.org/files/resources/COVID19/Diagnosis-asthma-COPD-during-Covid-19-v2-17-September-2020.pdf" target="_blank" title="click to follow the page">https://www.pcrs-uk.org/sites/pcrs-uk.org/files/resources/COVID19/Diagnosis-asthma-COPD-during-Covid-19-v2-17-September-2020.pdf</a></p>
					<p>9. Public Health England. 091.010 NObreath Accessories Mouthpiece Performance Test Report. London: Public Health England; 2009.</p>
					<p>10. Public Health England. An Evaluation of Filtration Efficiencies Against Bacterial and Viral Aerosol Challenges. Salisbury: Public Health England; 2020.</p>
					<p>11. Public Health England. An Evaluation of Filtration Efficiencies Against Bacterial and Viral Aerosol Challenges. London: Public Health England; 2017.</p>
					<p>12. Public Health England. An evaluation of Filtration Efficiencies Against Bacterial and Viral Aerosol Challenges. London: public Health England; 2020</p>
					<p>13. COVID-19: Guidance for maintaining services within health and care settings [Internet]. Assets.publishing.service.gov.uk. 2021 [cited 26 January 2021]. Available from: <a href="https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/954690/Infection_Prevention_and_Control_Guidance_January_2021.pdf" target="_blank" title="click to follow the page">https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/954690/Infection_Prevention_and_Control_Guidance_January_2021.pdf</a></p>
				</div>
			</div>
		</div>
	</section>

<?php
get_footer('');